name: properties
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  cached_network_image: ^3.2.1
  cloud_firestore: ^4.8.1
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  equatable: ^2.0.5
  file_picker: ^5.2.4
  firebase_auth: ^4.6.3
  firebase_core: ^2.13.1
  firebase_database: ^10.2.3
  firebase_storage: ^11.2.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_native_image: ^0.0.6+1
  flutter_native_splash: ^2.2.9
  flutter_speed_dial: ^6.2.0
  flutter_spinkit: ^5.1.0
  flutter_typeahead: ^4.1.1
  fluttertoast: ^8.2.2
  font_awesome_flutter: ^10.4.0
  geocoding: ^2.1.0
  geolocator: ^9.0.2
  get_it: ^7.6.0
  go_router: ^7.0.1
  google_fonts: ^4.0.1
  google_sign_in: ^6.1.4
  image_cropper: ^3.0.1
  image_picker: ^0.8.6+1
  image_watermark: ^0.0.5
  internet_connection_checker: ^0.0.1+2
  intl: any
  location: ^4.4.0
  path_provider: ^2.0.11
  permission_handler: ^10.3.0
  photo_view: ^0.14.0
  pinput: ^2.2.31
  provider: ^6.0.5
  pull_to_refresh: ^2.0.0
  shared_preferences: ^2.0.15
  shimmer: ^2.0.0
  timeago: ^3.3.0
  url_launcher: ^6.1.7
  uuid: ^3.0.7
  video_player: ^2.5.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/estate_icon.png
    - assets/flags/
    - assets/json/

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
